// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface CreateImovelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreateImovelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Imovel imovel = 1;</code>
   */
  boolean hasImovel();
  /**
   * <code>.proto.Imovel imovel = 1;</code>
   */
  proto.Imovel getImovel();
  /**
   * <code>.proto.Imovel imovel = 1;</code>
   */
  proto.ImovelOrBuilder getImovelOrBuilder();
}
