// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface GetImovelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetImovelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 imovelId = 1;</code>
   */
  int getImovelId();
}
