// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface GetImovelByPrecoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetImovelByPrecoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float precoInicial = 1;</code>
   */
  float getPrecoInicial();

  /**
   * <code>float precoFinal = 2;</code>
   */
  float getPrecoFinal();
}
