// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface GetImovelByTituloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetImovelByTituloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string titulo = 2;</code>
   */
  java.lang.String getTitulo();
  /**
   * <code>string titulo = 2;</code>
   */
  com.google.protobuf.ByteString
      getTituloBytes();
}
