// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface GetImovelByEnderecoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetImovelByEnderecoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Imovel imovel = 1;</code>
   */
  java.util.List<proto.Imovel> 
      getImovelList();
  /**
   * <code>repeated .proto.Imovel imovel = 1;</code>
   */
  proto.Imovel getImovel(int index);
  /**
   * <code>repeated .proto.Imovel imovel = 1;</code>
   */
  int getImovelCount();
  /**
   * <code>repeated .proto.Imovel imovel = 1;</code>
   */
  java.util.List<? extends proto.ImovelOrBuilder> 
      getImovelOrBuilderList();
  /**
   * <code>repeated .proto.Imovel imovel = 1;</code>
   */
  proto.ImovelOrBuilder getImovelOrBuilder(
      int index);
}
