// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

/**
 * Protobuf type {@code proto.GetImovelByPrecoRequest}
 */
public  final class GetImovelByPrecoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetImovelByPrecoRequest)
    GetImovelByPrecoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetImovelByPrecoRequest.newBuilder() to construct.
  private GetImovelByPrecoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetImovelByPrecoRequest() {
    precoInicial_ = 0F;
    precoFinal_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetImovelByPrecoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            precoInicial_ = input.readFloat();
            break;
          }
          case 21: {

            precoFinal_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.ImovelOuterClass.internal_static_proto_GetImovelByPrecoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.ImovelOuterClass.internal_static_proto_GetImovelByPrecoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.GetImovelByPrecoRequest.class, proto.GetImovelByPrecoRequest.Builder.class);
  }

  public static final int PRECOINICIAL_FIELD_NUMBER = 1;
  private float precoInicial_;
  /**
   * <code>float precoInicial = 1;</code>
   */
  public float getPrecoInicial() {
    return precoInicial_;
  }

  public static final int PRECOFINAL_FIELD_NUMBER = 2;
  private float precoFinal_;
  /**
   * <code>float precoFinal = 2;</code>
   */
  public float getPrecoFinal() {
    return precoFinal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (precoInicial_ != 0F) {
      output.writeFloat(1, precoInicial_);
    }
    if (precoFinal_ != 0F) {
      output.writeFloat(2, precoFinal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (precoInicial_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, precoInicial_);
    }
    if (precoFinal_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, precoFinal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.GetImovelByPrecoRequest)) {
      return super.equals(obj);
    }
    proto.GetImovelByPrecoRequest other = (proto.GetImovelByPrecoRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getPrecoInicial())
        == java.lang.Float.floatToIntBits(
            other.getPrecoInicial()));
    result = result && (
        java.lang.Float.floatToIntBits(getPrecoFinal())
        == java.lang.Float.floatToIntBits(
            other.getPrecoFinal()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRECOINICIAL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPrecoInicial());
    hash = (37 * hash) + PRECOFINAL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPrecoFinal());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.GetImovelByPrecoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GetImovelByPrecoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.GetImovelByPrecoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GetImovelByPrecoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.GetImovelByPrecoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GetImovelByPrecoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetImovelByPrecoRequest)
      proto.GetImovelByPrecoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ImovelOuterClass.internal_static_proto_GetImovelByPrecoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ImovelOuterClass.internal_static_proto_GetImovelByPrecoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GetImovelByPrecoRequest.class, proto.GetImovelByPrecoRequest.Builder.class);
    }

    // Construct using proto.GetImovelByPrecoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      precoInicial_ = 0F;

      precoFinal_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.ImovelOuterClass.internal_static_proto_GetImovelByPrecoRequest_descriptor;
    }

    @java.lang.Override
    public proto.GetImovelByPrecoRequest getDefaultInstanceForType() {
      return proto.GetImovelByPrecoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public proto.GetImovelByPrecoRequest build() {
      proto.GetImovelByPrecoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.GetImovelByPrecoRequest buildPartial() {
      proto.GetImovelByPrecoRequest result = new proto.GetImovelByPrecoRequest(this);
      result.precoInicial_ = precoInicial_;
      result.precoFinal_ = precoFinal_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.GetImovelByPrecoRequest) {
        return mergeFrom((proto.GetImovelByPrecoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.GetImovelByPrecoRequest other) {
      if (other == proto.GetImovelByPrecoRequest.getDefaultInstance()) return this;
      if (other.getPrecoInicial() != 0F) {
        setPrecoInicial(other.getPrecoInicial());
      }
      if (other.getPrecoFinal() != 0F) {
        setPrecoFinal(other.getPrecoFinal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.GetImovelByPrecoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.GetImovelByPrecoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float precoInicial_ ;
    /**
     * <code>float precoInicial = 1;</code>
     */
    public float getPrecoInicial() {
      return precoInicial_;
    }
    /**
     * <code>float precoInicial = 1;</code>
     */
    public Builder setPrecoInicial(float value) {
      
      precoInicial_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float precoInicial = 1;</code>
     */
    public Builder clearPrecoInicial() {
      
      precoInicial_ = 0F;
      onChanged();
      return this;
    }

    private float precoFinal_ ;
    /**
     * <code>float precoFinal = 2;</code>
     */
    public float getPrecoFinal() {
      return precoFinal_;
    }
    /**
     * <code>float precoFinal = 2;</code>
     */
    public Builder setPrecoFinal(float value) {
      
      precoFinal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float precoFinal = 2;</code>
     */
    public Builder clearPrecoFinal() {
      
      precoFinal_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GetImovelByPrecoRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.GetImovelByPrecoRequest)
  private static final proto.GetImovelByPrecoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.GetImovelByPrecoRequest();
  }

  public static proto.GetImovelByPrecoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetImovelByPrecoRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetImovelByPrecoRequest>() {
    @java.lang.Override
    public GetImovelByPrecoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetImovelByPrecoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetImovelByPrecoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetImovelByPrecoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.GetImovelByPrecoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

