// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

/**
 * Protobuf type {@code proto.GetImovelResponse}
 */
public  final class GetImovelResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetImovelResponse)
    GetImovelResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetImovelResponse.newBuilder() to construct.
  private GetImovelResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetImovelResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetImovelResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            proto.Imovel.Builder subBuilder = null;
            if (imovel_ != null) {
              subBuilder = imovel_.toBuilder();
            }
            imovel_ = input.readMessage(proto.Imovel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(imovel_);
              imovel_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.ImovelOuterClass.internal_static_proto_GetImovelResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.ImovelOuterClass.internal_static_proto_GetImovelResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.GetImovelResponse.class, proto.GetImovelResponse.Builder.class);
  }

  public static final int IMOVEL_FIELD_NUMBER = 1;
  private proto.Imovel imovel_;
  /**
   * <code>.proto.Imovel imovel = 1;</code>
   */
  public boolean hasImovel() {
    return imovel_ != null;
  }
  /**
   * <code>.proto.Imovel imovel = 1;</code>
   */
  public proto.Imovel getImovel() {
    return imovel_ == null ? proto.Imovel.getDefaultInstance() : imovel_;
  }
  /**
   * <code>.proto.Imovel imovel = 1;</code>
   */
  public proto.ImovelOrBuilder getImovelOrBuilder() {
    return getImovel();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (imovel_ != null) {
      output.writeMessage(1, getImovel());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (imovel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImovel());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.GetImovelResponse)) {
      return super.equals(obj);
    }
    proto.GetImovelResponse other = (proto.GetImovelResponse) obj;

    boolean result = true;
    result = result && (hasImovel() == other.hasImovel());
    if (hasImovel()) {
      result = result && getImovel()
          .equals(other.getImovel());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImovel()) {
      hash = (37 * hash) + IMOVEL_FIELD_NUMBER;
      hash = (53 * hash) + getImovel().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.GetImovelResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetImovelResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetImovelResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetImovelResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetImovelResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetImovelResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetImovelResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GetImovelResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GetImovelResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.GetImovelResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GetImovelResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GetImovelResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.GetImovelResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GetImovelResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetImovelResponse)
      proto.GetImovelResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ImovelOuterClass.internal_static_proto_GetImovelResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ImovelOuterClass.internal_static_proto_GetImovelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GetImovelResponse.class, proto.GetImovelResponse.Builder.class);
    }

    // Construct using proto.GetImovelResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (imovelBuilder_ == null) {
        imovel_ = null;
      } else {
        imovel_ = null;
        imovelBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.ImovelOuterClass.internal_static_proto_GetImovelResponse_descriptor;
    }

    @java.lang.Override
    public proto.GetImovelResponse getDefaultInstanceForType() {
      return proto.GetImovelResponse.getDefaultInstance();
    }

    @java.lang.Override
    public proto.GetImovelResponse build() {
      proto.GetImovelResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.GetImovelResponse buildPartial() {
      proto.GetImovelResponse result = new proto.GetImovelResponse(this);
      if (imovelBuilder_ == null) {
        result.imovel_ = imovel_;
      } else {
        result.imovel_ = imovelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.GetImovelResponse) {
        return mergeFrom((proto.GetImovelResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.GetImovelResponse other) {
      if (other == proto.GetImovelResponse.getDefaultInstance()) return this;
      if (other.hasImovel()) {
        mergeImovel(other.getImovel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.GetImovelResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.GetImovelResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private proto.Imovel imovel_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.Imovel, proto.Imovel.Builder, proto.ImovelOrBuilder> imovelBuilder_;
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public boolean hasImovel() {
      return imovelBuilder_ != null || imovel_ != null;
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public proto.Imovel getImovel() {
      if (imovelBuilder_ == null) {
        return imovel_ == null ? proto.Imovel.getDefaultInstance() : imovel_;
      } else {
        return imovelBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public Builder setImovel(proto.Imovel value) {
      if (imovelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imovel_ = value;
        onChanged();
      } else {
        imovelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public Builder setImovel(
        proto.Imovel.Builder builderForValue) {
      if (imovelBuilder_ == null) {
        imovel_ = builderForValue.build();
        onChanged();
      } else {
        imovelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public Builder mergeImovel(proto.Imovel value) {
      if (imovelBuilder_ == null) {
        if (imovel_ != null) {
          imovel_ =
            proto.Imovel.newBuilder(imovel_).mergeFrom(value).buildPartial();
        } else {
          imovel_ = value;
        }
        onChanged();
      } else {
        imovelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public Builder clearImovel() {
      if (imovelBuilder_ == null) {
        imovel_ = null;
        onChanged();
      } else {
        imovel_ = null;
        imovelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public proto.Imovel.Builder getImovelBuilder() {
      
      onChanged();
      return getImovelFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    public proto.ImovelOrBuilder getImovelOrBuilder() {
      if (imovelBuilder_ != null) {
        return imovelBuilder_.getMessageOrBuilder();
      } else {
        return imovel_ == null ?
            proto.Imovel.getDefaultInstance() : imovel_;
      }
    }
    /**
     * <code>.proto.Imovel imovel = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.Imovel, proto.Imovel.Builder, proto.ImovelOrBuilder> 
        getImovelFieldBuilder() {
      if (imovelBuilder_ == null) {
        imovelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.Imovel, proto.Imovel.Builder, proto.ImovelOrBuilder>(
                getImovel(),
                getParentForChildren(),
                isClean());
        imovel_ = null;
      }
      return imovelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GetImovelResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.GetImovelResponse)
  private static final proto.GetImovelResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.GetImovelResponse();
  }

  public static proto.GetImovelResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetImovelResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetImovelResponse>() {
    @java.lang.Override
    public GetImovelResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetImovelResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetImovelResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetImovelResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.GetImovelResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

