// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface GetImovelByEnderecoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetImovelByEnderecoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string endereco = 2;</code>
   */
  java.lang.String getEndereco();
  /**
   * <code>string endereco = 2;</code>
   */
  com.google.protobuf.ByteString
      getEnderecoBytes();
}
