// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imovel.proto

package proto;

public interface ListImovelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListImovelRequest)
    com.google.protobuf.MessageOrBuilder {
}
